#!/bin/sh
#
# Copyright (c) 2010, Adrian Friedli
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.

# Installation
#
# Create the directory /var/cache/pbuilder/btrfs and mount there (or anywhere
# above in the file system tree) a btrfs file system.
#
# Make sure you have this in /etc/pbuilderrc or any other pbuilder config file,
# as hardlinks between subvolumes are not allowed:
#
# APTCACHEHARDLINK=no

set -e

BTRFSPATH="/var/cache/pbuilder/btrfs"
BASEPATH="$BTRFSPATH/base"
BUILDPLACE="$BTRFSPATH/$$"
ACTION="$1"; [ -n "$1" ] && shift

pbuilder_run()
{
	pbuilder "$ACTION" --buildplace "$BUILDPLACE" --no-targz "$@" || \
	{
		RES=$?
		btrfs_delete
		return $RES
	}
}

btrfs_snapshot() { btrfs subvolume snapshot "$BASEPATH" "$BUILDPLACE"; }
btrfs_delete() { btrfs subvolume delete "${1:-"$BUILDPLACE"}"; }

case "$ACTION" in
    --create|create)
	btrfs subvolume create "$BASEPATH"
	BUILDPLACE="$BASEPATH"
	pbuilder_run "$@"
	;;
    --update|update)
	btrfs_snapshot
	pbuilder_run "$@"
	btrfs_delete "$BASEPATH"
	mv "$BUILDPLACE" "$BASEPATH"
	;;
    --build|build|--login|login|--execute|execute|--debuild|debuild)
	btrfs_snapshot
	pbuilder_run "$@"
	btrfs_delete
	;;
    --clean|clean)
	BUILDPLACE="$BASEPATH"
	pbuilder_run "$@"
	btrfs_delete
	;;
    --dumpconfig|dumpconfig)
	echo "not implemented"
	exit 1
	;;
    *)
	echo "not a valid command"
	exit 1
	;;
esac
